### ISSUE TITLE
⚠️ COST! This soution provisions 9 VPC endpoints in all available subnets

### ISSUE THREAD

**Issue by vavdoshka** [aws-samples/aws-batch-with-ffmpeg#17]
This Cost info is misleading here https://github.com/aws-samples/aws-batch-with-ffmpeg#cost

If deployed in us-east-1 with 6 AZs, the cost of running 9 endpoints in all zones is around 12$ per day.
Where there is no added value from having these endpoints.

https://github.com/aws-samples/aws-batch-with-ffmpeg/blob/5a7e8db9a420ad7adbe5da88c06961c7923d9353/cdk/landing_zone_stack.py#L49-L114

**Comment by gmarchand** [comment]
You're right, I am going to fix this. Thanks for the feedback

**Comment by gmarchand** [comment]
Fixed : https://github.com/aws-samples/aws-batch-with-ffmpeg/releases/tag/v0.0.7
